# Generated by Django 4.2.5 on 2023-10-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcworld', '0007_component'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='component',
            name='fulldesc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='img',
            field=models.ImageField(upload_to='component_img'),
        ),
    ]
