# Generated by Django 4.2.5 on 2023-12-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcworld', '0011_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=2000),
        ),
    ]
